# Generated by Django 4.1.13 on 2024-02-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('published_datetime', models.DateTimeField()),
                ('thumbnail_urls', models.JSONField()),
            ],
        ),
    ]
